---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tazblog
  labels:
    app: tazblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tazblog
  template:
    metadata:
      labels:
        app: tazblog
    spec:
      containers:
      - name: tazblog
        image: nixery.local/shell/tazjin.blog:{{ gitHEAD }}
        command: [ "tazblog" ]
---
apiVersion: v1
kind: Service
metadata:
  name: tazblog
spec:
  type: NodePort
  selector:
    app: tazblog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
